version: '3'
services:
  app:
    container_name: firstproject
    build: .
    depends_on:
      - db
    ports: 
      - 8080:8080 
    restart: on-failure
    environment:
      MYSQL_DBNAME: dbproject1
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  db:
    image: mysql:latest
    container_name: dockerMySQL
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dbproject1
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-ppassword", "-e", "show schemas"]
      interval: 10s 